### ISSUE TITLE
[question] pointless test?

### ISSUE THREAD

**Issue by chpio** [CleverCloud/uuid_to_pokemon.rs#2]
What's the purpose of this test:
https://github.com/CleverCloud/uuid_to_pokemon.rs/blob/d80afe7a6c700ede07c369cb55c8fe9677bbdf78/src/lib.rs#L1002-L1016

Looks like dead code to me.

**Comment by divarvel** [comment]
It's a regression test from the nodeJS version, which introduced randomness at some point.
We want the output to be determinist.

**Comment by chpio** [comment]
hmm, yeah you're right. What's this JS version and where can i find it? I searched on npm but couldn't find it there.
